### PR TITLE
Updated for Vapor 2.0 pre-release

### PR DESCRIPTION
**Pull request by ksmandersen**

### CODE REVIEW

**Comment by ksmandersen** [comment]
Seems that it still wants to merge on JustinM1:master 🤔 Not sure what I am doing wrong here

**Comment by JustinM1** [comment]
I added a Vapor2 branch, you should be good to go now.

**Comment by ksmandersen** [comment]
@JustinM1 Should be on the right branch now

**Comment by JustinM1** [comment]
done, thanks for contributing @ksmandersen!

**Comment by Yasumoto** [comment]
👏

**Pull request merged**
